# Generated by Django 3.2.7 on 2021-12-02 21:53

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo_blog', models.CharField(help_text='Titulo principal. Maximo 30 caracteres. ', max_length=30)),
                ('fecha_publicacion', models.DateField(help_text='Fecha de publicacion del post.')),
                ('autor', models.CharField(blank=True, help_text='Nombre del autor. -Opcional ', max_length=30, null=True)),
                ('contenido_blog', wagtail.core.fields.RichTextField(blank=True, help_text='Escriba aqui el contenido de su post. Maximo 5000 caracteres.', max_length=5000)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ImagenFondoBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('imagen_blog', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='fondo_blog', to='blog.blogpost')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
