# Generated by Django 3.2.7 on 2021-12-02 21:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0062_comment_models_and_pagesubscription'),
        ('wagtailimages', '0023_add_choose_permissions'),
        ('wagtaildocs', '0012_uploadeddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo_servicio', models.CharField(help_text='Titulo del servicio. Maximo de 30 caracteres', max_length=30)),
                ('resumen_servicio', models.CharField(help_text='Breve descripcion de su servicio. Maximo de 100 caracteres.', max_length=100)),
                ('icono_servicio', models.ForeignKey(help_text='Usar formato PNG una resolucio de 45px X 45px.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nosotros',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('titulo_nosotros', models.CharField(max_length=40)),
                ('subtitulo_nosotros', models.CharField(blank=True, max_length=100, null=True)),
                ('texto_nosotros', wagtail.core.fields.RichTextField(blank=True, help_text='Escribe aqui el texto para la seccion de nosotros. Maximo 1500 caracteres', max_length=1500)),
                ('folleto', models.ForeignKey(blank=True, help_text='Subir un documento en formato pdf', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.document')),
                ('nosotros_imagen', models.ForeignKey(help_text='Resolucion optima 800px X 820px ', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LogoClientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('logo_cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='logo_image', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImageHome',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('titulo_principal', models.CharField(blank=True, max_length=30, null=True)),
                ('subtitulo', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen_fondo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_image', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('correo_electronico', models.EmailField(help_text='Escribe aqui el correo electronico de contacto', max_length=254)),
                ('numero_contacto', models.CharField(blank=True, help_text='Numero de contacto. Direcciona hacia WhatsApp', max_length=10, null=True, validators=[django.core.validators.RegexValidator('^\\d{1,10}$')])),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicacion de su empresa. Maximo de 100 caracteres.', max_length=100)),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClienteOpinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('opnion_cliente', wagtail.core.fields.RichTextField(help_text='Escribe aqui una breve opinion de tu cliente. Maximo 600 caracteres', max_length=600)),
                ('nombre_cliente', models.CharField(help_text='Nombre del cliente o empresa. Maximo 40 caracteres.', max_length=40)),
                ('trabajo_realizado', models.CharField(help_text='Trabajo que se le realizo al cliente', max_length=40)),
                ('imagen_cliente', models.ForeignKey(help_text='Resolucion optima 600px X 600px', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_image', to='home.homepage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
